name: owl-top-app-actions

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/fwrelik/owl-top-app/owl-top-app
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: develop
